=== ibressler/qsldcalc/res/data/chemical_elements.dtd
<!ELEMENT chemical_element_list (chemical_element*)>

<!ELEMENT chemical_element (
	name,
	abundance,
	atomic_weight,
	nucleons?,
	electrons,
	neutron_scattering_length?,
	neutron_scattering_cross_section?,
	xray_scattering_anomalous_coefficients?
)>
<!ATTLIST chemical_element
	symbol	CDATA	#REQUIRED
>

<!ELEMENT atomic_weight EMPTY>
<!ATTLIST atomic_weight
	val	CDATA	#REQUIRED
	unit	CDATA	"g/mol"
>

<!ELEMENT nucleons EMPTY>
<!ATTLIST nucleons
	val	CDATA	#REQUIRED
>

<!ELEMENT name EMPTY>
<!ATTLIST name
	val	CDATA	#REQUIRED
>

<!ELEMENT electrons EMPTY>
<!ATTLIST electrons
	val	CDATA	#REQUIRED
>

<!ELEMENT abundance EMPTY>
<!ATTLIST abundance
	val	CDATA	#REQUIRED
>

<!ELEMENT neutron_scattering_length (coherent?, incoherent?)>
<!ATTLIST neutron_scattering_length
	factor	CDATA	"1e-15"
	unit	CDATA	"m"
>

<!ELEMENT neutron_scattering_cross_section (coherent?, incoherent?, total?, absorption?)>
<!ATTLIST neutron_scattering_cross_section
	factor	CDATA	"1e-24"
	unit	CDATA	"cmÂ²"
>

<!ELEMENT coherent EMPTY>
<!ATTLIST coherent
	re	CDATA	#REQUIRED
	im	CDATA	"0.0"
>

<!ELEMENT incoherent EMPTY>
<!ATTLIST incoherent
	re	CDATA	#REQUIRED
	im	CDATA	"0.0"
>

<!ELEMENT total EMPTY>
<!ATTLIST total
	val	CDATA	#REQUIRED
>

<!-- absorption cross section for 2200 m/s neutrons -->
<!ELEMENT absorption EMPTY>
<!ATTLIST absorption
	val	CDATA	#REQUIRED
>

<!ELEMENT xray_scattering_anomalous_coefficients (ev*)>
<!ATTLIST xray_scattering_anomalous_coefficients
	unit	CDATA	"keV"
>

<!ELEMENT ev EMPTY>
<!ATTLIST ev
	val	CDATA	#REQUIRED
	fp	CDATA	#REQUIRED
	fpp	CDATA	#REQUIRED
>

=== ibressler/qsldcalc/res/data/Am.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chemical_element_list SYSTEM "chemical_elements.dtd">
<chemical_element_list>
	<chemical_element symbol="Am">
		<name val="Americium"/>
		<abundance val="100"/>
		<atomic_weight val="243.0613727"/>
		<nucleons val="-1"/>
		<electrons val="95"/>
		<neutron_scattering_length>
			<coherent re="8.3"/>
			<incoherent re="2"/>
		</neutron_scattering_length>
		<neutron_scattering_cross_section>
			<coherent re="8.7"/>
			<incoherent re="0.3"/>
			<total val="9"/>
			<absorption val="75.3"/>
		</neutron_scattering_cross_section>
	</chemical_element>
	<chemical_element symbol="Am">
		<name val="Americium"/>
		<abundance val="0"/>
		<atomic_weight val="243.0613727"/>
		<nucleons val="243"/>
		<electrons val="95"/>
		<neutron_scattering_length>
			<coherent re="8.3"/>
			<incoherent re="2"/>
		</neutron_scattering_length>
		<neutron_scattering_cross_section>
			<coherent re="8.7"/>
			<incoherent re="0.3"/>
			<total val="9"/>
			<absorption val="75.3"/>
		</neutron_scattering_cross_section>
	</chemical_element>
</chemical_element_list>

=== ibressler/qsldcalc/res/data/Pu.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chemical_element_list SYSTEM "chemical_elements.dtd">
<chemical_element_list>
	<chemical_element symbol="Pu">
		<name val="Plutonium"/>
		<abundance val="100"/>
		<atomic_weight val="244.064198"/>
		<nucleons val="-1"/>
		<electrons val="94"/>
	</chemical_element>
	<chemical_element symbol="Pu">
		<name val="Plutonium"/>
		<abundance val="0"/>
		<atomic_weight val="238.0495534"/>
		<nucleons val="238"/>
		<electrons val="94"/>
		<neutron_scattering_length>
			<coherent re="14.1"/>
		</neutron_scattering_length>
		<neutron_scattering_cross_section>
			<coherent re="25"/>
			<total val="25"/>
			<absorption val="558"/>
		</neutron_scattering_cross_section>
	</chemical_element>
	<chemical_element symbol="Pu">
		<name val="Plutonium"/>
		<abundance val="0"/>
		<atomic_weight val="239.0521565"/>
		<nucleons val="239"/>
		<electrons val="94"/>
		<neutron_scattering_length>
			<coherent re="7.7"/>
			<incoherent re="1.3"/>
		</neutron_scattering_length>
		<neutron_scattering_cross_section>
			<coherent re="7.5"/>
			<incoherent re="0.2"/>
			<total val="7.7"/>
			<absorption val="1017.3"/>
		</neutron_scattering_cross_section>
	</chemical_element>
	<chemical_element symbol="Pu">
		<name val="Plutonium"/>
		<abundance val="0"/>
		<atomic_weight val="240.0538075"/>
		<nucleons val="240"/>
		<electrons val="94"/>
		<neutron_scattering_length>
			<coherent re="3.5"/>
		</neutron_scattering_length>
		<neutron_scattering_cross_section>
			<coherent re="1.54"/>
			<total val="1.54"/>
			<absorption val="289.6"/>
		</neutron_scattering_cross_section>
	</chemical_element>
	<chemical_element symbol="Pu">
		<name val="Plutonium"/>
		<abundance val="0"/>
		<atomic_weight val="242.0587368"/>
		<nucleons val="242"/>
		<electrons val="94"/>
		<neutron_scattering_length>
			<coherent re="8.1"/>
		</neutron_scattering_length>
		<neutron_scattering_cross_section>
			<coherent re="8.2"/>
			<total val="8.2"/>
			<absorption val="18.5"/>
		</neutron_scattering_cross_section>
	</chemical_element>
</chemical_element_list>

=== ibressler/qsldcalc/res/data/Cm.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chemical_element_list SYSTEM "chemical_elements.dtd">
<chemical_element_list>
	<chemical_element symbol="Cm">
		<name val="Curium"/>
		<abundance val="100"/>
		<atomic_weight val="247.070347"/>
		<nucleons val="-1"/>
		<electrons val="96"/>
	</chemical_element>
	<chemical_element symbol="Cm">
		<name val="Curium"/>
		<abundance val="0"/>
		<atomic_weight val="244.0627463"/>
		<nucleons val="244"/>
		<electrons val="96"/>
		<neutron_scattering_length>
			<coherent re="9.5"/>
		</neutron_scattering_length>
		<neutron_scattering_cross_section>
			<coherent re="11.3"/>
			<total val="11.3"/>
			<absorption val="16.2"/>
		</neutron_scattering_cross_section>
	</chemical_element>
	<chemical_element symbol="Cm">
		<name val="Curium"/>
		<abundance val="0"/>
		<atomic_weight val="246.0672176"/>
		<nucleons val="246"/>
		<electrons val="96"/>
		<neutron_scattering_length>
			<coherent re="9.3"/>
		</neutron_scattering_length>
		<neutron_scattering_cross_section>
			<coherent re="10.9"/>
			<total val="10.9"/>
			<absorption val="1.36"/>
		</neutron_scattering_cross_section>
	</chemical_element>
	<chemical_element symbol="Cm">
		<name val="Curium"/>
		<abundance val="0"/>
		<atomic_weight val="248.072342"/>
		<nucleons val="248"/>
		<electrons val="96"/>
		<neutron_scattering_length>
			<coherent re="7.7"/>
		</neutron_scattering_length>
		<neutron_scattering_cross_section>
			<coherent re="7.5"/>
			<total val="7.5"/>
			<absorption val="3"/>
		</neutron_scattering_cross_section>
	</chemical_element>
</chemical_element_list>

=== ibressler/qsldcalc/res/data/Np.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chemical_element_list SYSTEM "chemical_elements.dtd">
<chemical_element_list>
	<chemical_element symbol="Np">
		<name val="Neptunium"/>
		<abundance val="100"/>
		<atomic_weight val="237.0481673"/>
		<nucleons val="-1"/>
		<electrons val="93"/>
		<neutron_scattering_length>
			<coherent re="10.55"/>
		</neutron_scattering_length>
		<neutron_scattering_cross_section>
			<coherent re="14"/>
			<incoherent re="0.5"/>
			<total val="14.5"/>
			<absorption val="175.9"/>
		</neutron_scattering_cross_section>
	</chemical_element>
	<chemical_element symbol="Np">
		<name val="Neptunium"/>
		<abundance val="0"/>
		<atomic_weight val="237.0481673"/>
		<nucleons val="237"/>
		<electrons val="93"/>
		<neutron_scattering_length>
			<coherent re="10.55"/>
		</neutron_scattering_length>
		<neutron_scattering_cross_section>
			<coherent re="14"/>
			<incoherent re="0.5"/>
			<total val="14.5"/>
			<absorption val="175.9"/>
		</neutron_scattering_cross_section>
	</chemical_element>
</chemical_element_list>
